/**
 * Renders the deterministic investigation plan (`investigation-planner.ts`)
 * generated by `start_investigation` — an ordered checklist with real
 * pending/done/skipped status, never a fabricated progress bar.
 */

import { cn } from "@aipexstudio/aipex-react/lib/utils";
import type { InvestigationPlan } from "@aipexstudio/browser-runtime";

const STATUS_SYMBOL: Record<
  "pending" | "done" | "skipped",
  { symbol: string; className: string }
> = {
  pending: { symbol: "○", className: "text-muted-foreground" },
  done: { symbol: "✓", className: "text-green-600 dark:text-green-400" },
  skipped: { symbol: "—", className: "text-muted-foreground" },
};

export function PlanChecklist({
  plan,
}: {
  plan: InvestigationPlan | undefined;
}) {
  if (!plan) {
    return (
      <p className="px-2 py-4 text-center text-sm text-muted-foreground">
        No plan generated for this investigation.
      </p>
    );
  }

  const doneCount = plan.steps.filter((s) => s.status === "done").length;

  return (
    <div className="space-y-2">
      <p className="px-1 text-xs text-muted-foreground">
        {doneCount}/{plan.steps.length} steps done · pattern: {plan.category}
      </p>
      <ol className="space-y-1">
        {plan.steps.map((step) => {
          const meta = STATUS_SYMBOL[step.status];
          return (
            <li
              key={step.id}
              className={cn(
                "flex items-start gap-2 rounded-md px-2 py-1 text-sm",
                step.status === "skipped" && "opacity-60",
              )}
            >
              <span
                className={cn("mt-0.5 shrink-0 font-semibold", meta.className)}
              >
                {meta.symbol}
              </span>
              <span
                className={cn(
                  step.status === "done" &&
                    "line-through text-muted-foreground",
                )}
              >
                {step.description}
              </span>
            </li>
          );
        })}
      </ol>
    </div>
  );
}
