/**
 * Renders the deterministic investigation plan (`investigation-planner.ts`)
 * generated by `start_investigation` — an ordered checklist with real
 * pending/done/skipped status, never a fabricated progress bar.
 */

import type { InvestigationPlan } from "@apty/browser-runtime";
import { Progress } from "@apty/ui/components/ui/progress";
import { cn } from "@apty/ui/lib/utils";
import { toneBadgeClass } from "./tone-classes";

const STATUS_MARKER: Record<
  "pending" | "done" | "skipped",
  { symbol: (index: number) => string; className: string }
> = {
  pending: {
    symbol: (index) => String(index + 1),
    className: "border-border text-muted-foreground",
  },
  done: { symbol: () => "✓", className: toneBadgeClass("success") },
  skipped: {
    symbol: () => "–",
    className: "border-border text-muted-foreground",
  },
};

export function PlanChecklist({
  plan,
}: {
  plan: InvestigationPlan | undefined;
}) {
  if (!plan) {
    return (
      <p className="px-2 py-4 text-center text-sm text-muted-foreground">
        No plan generated for this investigation.
      </p>
    );
  }

  const doneCount = plan.steps.filter((s) => s.status === "done").length;
  const progress =
    plan.steps.length > 0 ? (doneCount / plan.steps.length) * 100 : 0;

  return (
    <div className="space-y-2">
      <div className="space-y-1 px-1">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>
            {doneCount}/{plan.steps.length} steps done
          </span>
          <span className="capitalize">{plan.category.replace(/_/g, " ")}</span>
        </div>
        <Progress value={progress} className="h-1" />
      </div>
      <ol className="space-y-1">
        {plan.steps.map((step, index) => {
          const marker = STATUS_MARKER[step.status];
          return (
            <li
              key={step.id}
              className={cn(
                "flex items-start gap-2.5 rounded-md px-2 py-1 text-sm transition-colors duration-300",
                step.status === "skipped" && "opacity-60",
              )}
            >
              <span
                className={cn(
                  "mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full border text-[11px] font-semibold transition-colors duration-300",
                  marker.className,
                )}
                aria-hidden="true"
              >
                {marker.symbol(index)}
              </span>
              <span
                className={cn(
                  "pt-0.5",
                  step.status === "done" &&
                    "line-through text-muted-foreground",
                )}
              >
                {step.description}
              </span>
            </li>
          );
        })}
      </ol>
    </div>
  );
}
